#!/usr/bin/env bash
# Intall and config Nginx in our remote server.

# Install Nginx if not already installed
if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y nginx
fi

# Create a custom index page.
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx service.
service nginx restart
