#!/usr/bin/env bash
# Intall and config Nginx in our remote server.

# Install Nginx if not already installed
if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y nginx
fi

# Create a custom 404 HTML page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Check if custom configuration already exists in Nginx server configuration
if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-available/default; then
  # Modify the Nginx default server configuration
  sed -i '/server_name _;/a \
          error_page 404 /404.html;\n \
          location = /404.html {\n \
              root /var/www/html;\n \
          }\n' /etc/nginx/sites-available/default

  # Restart Nginx
  service nginx restart
else
  # echo "Custom configuration already exists. Skipping..."
  # Restart Nginx
  service nginx restart
fi
