#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

# Install Nginx if not already installed
if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y nginx
fi

# backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

sed -i '/server_name _;/a \
        add_header X-Served-By \$hostname;\n' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
