#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install HAproxy if not already installed
if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y haproxy
fi

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup


server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 195416-web-01 54.160.120.200:80 check
    server 195416-web-02 54.145.155.255:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
