#!/usr/bin/env bash
# configures nginx server to be listening on port 80 
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx status | grep -q "not running"
