#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, with a special case on the 9th iteration
msg="Best School"
count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 8 ]
  then
    echo -e "$msg\nHi"
  else
    echo "$msg"
  fi

  count=$((count+1))
done
