#!/usr/bin/env bash
# This script displays the hours from 0 to 23 and the minutes from 1 to 59
hours=0

while [ $hours -lt 24 ]
do
  echo "Hour: $hours"

  minutes=1
  while [ $minutes -lt 60 ]
  do
    echo "$minutes"
    minutes=$((minutes+1))
  done

  hours=$((hours+1))
done
