#!/usr/bin/env bash
# Set Up a Firewall with UFW on Ubuntu.

# Update package lists and Install UFW
sudo apt update -qq
sudo apt install -y ufw

# Enable IPv6
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Set default incoming policy to deny
sudo ufw default deny incoming

# Set default outgoing policy to allow
sudo ufw default allow outgoing

# Check which profiles are currently registered in UFW
sudo ufw app list

# Allow SSH by Port Number (OpenSSH service)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443) and HTTP (port 80) traffic
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW
sudo ufw enable

# Display UFW status and rules
sudo ufw status
